run:
  # Number of operating system threads (`GOMAXPROCS`) that can execute golangci-lint simultaneously.
  # If it is explicitly set to 0 (i.e. not the default) then golangci-lint will automatically set the value to match Linux container CPU quota.
  # Default: the number of logical CPUs in the machine
  concurrency: 4
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m
output:
  formats:
    - format: colored-line-number
      path: stdout
    # - format: json
    #   path: output.json
  # Print lines of code with issue.
  # Default: true
  print-issued-lines: true
  # Print linter name in the end of issue text.
  # Default: true
  print-linter-name: true
  # Make issues output unique by line.
  # Default: true
  uniq-by-line: true
# linter configuration
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - unused
    - ineffassign
    - staticcheck 
    - errorlint
