name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test_js:
    env: 
      APP_ENV: ${{ secrets.APP_ENV }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      MESSAGE_BROKER_PROTOCOL: ${{ secrets.MESSAGE_BROKER_PROTOCOL }}
      MESSAGE_BROKER_USER: ${{ secrets.MESSAGE_BROKER_USER }}
      MESSAGE_BROKER_PASSWORD: ${{ secrets.MESSAGE_BROKER_PASSWORD }}
      MESSAGE_BROKER_VIRTUAL_HOST: ${{ secrets.MESSAGE_BROKER_VIRTUAL_HOST }}
      MESSAGE_BROKER_HOST: ${{ secrets.MESSAGE_BROKER_HOST }}
      MESSAGE_BROKER_PORT: ${{ secrets.MESSAGE_BROKER_PORT }}
      MESSAGE_BROKER_CLOUD: ${{ secrets.MESSAGE_BROKER_CLOUD }}
      EXCHANGE_PROCESS_SERVICE: ${{ secrets.EXCHANGE_PROCESS_SERVICE }}
      QUEUE_PROCESS_SERVICE: ${{ secrets.QUEUE_PROCESS_SERVICE }}
      ROUTING_KEY_PROCESS_SERVICE: ${{ secrets.ROUTING_KEY_PROCESS_SERVICE }}

    name: Testing JavaScript
    defaults:
      run:
        shell: bash
        working-directory: ./js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 'Checkout repository'
      
      - uses: oven-sh/setup-bun@v1
      - name: 'Install Dependencies'
        run: bun install
    
      - name: 'Run Tests'
        run: bun run test

  lint_js:
    env:
      APP_ENV: ${{ secrets.APP_ENV }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      MESSAGE_BROKER_PROTOCOL: ${{ secrets.MESSAGE_BROKER_PROTOCOL }}
      MESSAGE_BROKER_USER: ${{ secrets.MESSAGE_BROKER_USER }}
      MESSAGE_BROKER_PASSWORD: ${{ secrets.MESSAGE_BROKER_PASSWORD }}
      MESSAGE_BROKER_VIRTUAL_HOST: ${{ secrets.MESSAGE_BROKER_VIRTUAL_HOST }}
      MESSAGE_BROKER_HOST: ${{ secrets.MESSAGE_BROKER_HOST }}
      MESSAGE_BROKER_PORT: ${{ secrets.MESSAGE_BROKER_PORT }}
      MESSAGE_BROKER_CLOUD: ${{ secrets.MESSAGE_BROKER_CLOUD }}
      EXCHANGE_PROCESS_SERVICE: ${{ secrets.EXCHANGE_PROCESS_SERVICE }}
      QUEUE_PROCESS_SERVICE: ${{ secrets.QUEUE_PROCESS_SERVICE }}
      ROUTING_KEY_PROCESS_SERVICE: ${{ secrets.ROUTING_KEY_PROCESS_SERVICE }}

    name: Linting JavaScript
    defaults:
      run:
        shell: bash
        working-directory: ./js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: 'Checkout repository'
            
      - uses: oven-sh/setup-bun@v1
      - name: 'Install Dependencies'
        run: bun install
          
      - name: 'Run Lint'
        run: bunx eslint .
